# Generated by Django 4.1 on 2023-05-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ['last_name']},
        ),
    ]
